apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  POSTGRES_USER: dHN1LXVzZXI= #bas64: use echo -n 'key_here' | base64
  POSTGRES_PASSWORD: MTIzNDU2
  POSTGRES_DB: dHN1LWNvd29ya2luZy1kYg==